name: The field guide to successful drinking in America
favicon: null
layout_spectrum: 0.29149020137265325
typography_spectrum: 0.6687775345053524
title: The field guide to successful drinking in America
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.13790081162005663
  lightness: 0.40698775509372354
  saturation: 0.931008730083704
  rhythmicContrast: 0.0375663957092911
purpose: []
